version: 2
updates:
  # Monthly updates for regular dependencies
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'monthly'
      day: 'monday'
      time: '09:00'
    open-pull-requests-limit: 3
    reviewers:
      - 'aftongauntlett'
    assignees:
      - 'aftongauntlett'
    commit-message:
      prefix: 'chore'
      include: 'scope'
    labels:
      - 'dependencies'
      - 'automated'
    # Group related dependencies to reduce PR noise
    groups:
      development-dependencies:
        patterns:
          - '@types/*'
          - '@typescript-eslint/*'
          - 'eslint*'
          - 'vitest'
          - 'vite*'
          - '@vitejs/*'
          - 'prettier'
          - 'tailwindcss'
          - 'postcss'
          - 'autoprefixer'
      react-ecosystem:
        patterns:
          - 'react*'
          - '@testing-library/*'
      build-tools:
        patterns:
          - 'typescript'
          - 'rollup*'
      production-dependencies:
        patterns:
          - '*'
        exclude-patterns:
          - '@types/*'
          - '@typescript-eslint/*'
          - 'eslint*'
          - 'vitest'
          - 'vite*'
          - '@vitejs/*'
          - 'prettier'
          - 'tailwindcss'
          - 'postcss'
          - 'autoprefixer'
          - 'react*'
          - '@testing-library/*'
          - 'typescript'
          - 'rollup*'
    # Only allow patch and minor updates (safer)
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-major']
